/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class btBoxShape
 *
 * This file has been generated by dub 2.2.1.
 */
#include "dub/dub.h"
#include "BulletCollision/CollisionShapes/btBoxShape.h"


/** ~btBoxShape()
 * 
 */
static int btBoxShape__btBoxShape(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "bt.BoxShape"));
    if (userdata->gc) {
      btBoxShape *self = (btBoxShape *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** Cast (class_name)
 * 
 */
static int btBoxShape__cast_(lua_State *L) {

  btBoxShape *self = *((btBoxShape **)dub::checksdata_n(L, 1, "bt.BoxShape"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub::hash(key, 4);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "bt.PolyhedralConvexShape")) break;
      *retval__ = static_cast<btPolyhedralConvexShape *>(self);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "bt.ConvexInternalShape")) break;
      *retval__ = static_cast<btConvexInternalShape *>(self);
      return 1;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "bt.ConvexShape")) break;
      *retval__ = static_cast<btConvexShape *>(self);
      return 1;
    }
    case 3: {
      if (DUB_ASSERT_KEY(key, "bt.CollisionShape")) break;
      *retval__ = static_cast<btCollisionShape *>(self);
      return 1;
    }
  }
  return 0;
}

/** btVector3 btBoxShape::getHalfExtentsWithMargin() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:36
 */
static int btBoxShape_getHalfExtentsWithMargin(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    dub::pushudata(L, new btVector3(self->getHalfExtentsWithMargin()), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getHalfExtentsWithMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getHalfExtentsWithMargin: Unknown exception");
  }
  return dub::error(L);
}

/** const btVector3& btBoxShape::getHalfExtentsWithoutMargin() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:44
 */
static int btBoxShape_getHalfExtentsWithoutMargin(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    dub::pushudata(L, const_cast<btVector3*>(&self->getHalfExtentsWithoutMargin()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getHalfExtentsWithoutMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getHalfExtentsWithoutMargin: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btVector3 btBoxShape::localGetSupportingVertex(const btVector3 &vec) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:50
 */
static int btBoxShape_localGetSupportingVertex(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *vec = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    dub::pushudata(L, new btVector3(self->localGetSupportingVertex(*vec)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localGetSupportingVertex: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localGetSupportingVertex: Unknown exception");
  }
  return dub::error(L);
}

/** btVector3 btBoxShape::localGetSupportingVertexWithoutMargin(const btVector3 &vec) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:61
 */
static int btBoxShape_localGetSupportingVertexWithoutMargin(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *vec = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    dub::pushudata(L, new btVector3(self->localGetSupportingVertexWithoutMargin(*vec)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localGetSupportingVertexWithoutMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localGetSupportingVertexWithoutMargin: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::batchedUnitVectorGetSupportingVertexWithoutMargin(const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:70
 */
static int btBoxShape_batchedUnitVectorGetSupportingVertexWithoutMargin(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *vectors = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    btVector3 *supportVerticesOut = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    int numVectors = dub::checkint(L, 4);
    self->batchedUnitVectorGetSupportingVertexWithoutMargin(vectors, supportVerticesOut, numVectors);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "batchedUnitVectorGetSupportingVertexWithoutMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "batchedUnitVectorGetSupportingVertexWithoutMargin: Unknown exception");
  }
  return dub::error(L);
}

/** btBoxShape::btBoxShape(const btVector3 &boxHalfExtents)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:85
 */
static int btBoxShape_btBoxShape(lua_State *L) {
  try {
    btVector3 *boxHalfExtents = *((btVector3 **)dub::checksdata(L, 1, "bt.Vector3"));
    btBoxShape *retval__ = new btBoxShape(*boxHalfExtents);
    dub::pushudata(L, retval__, "bt.BoxShape", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::setMargin(btScalar collisionMargin)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:87
 */
static int btBoxShape_setMargin(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btScalar collisionMargin = dub::checknumber(L, 2);
    self->setMargin(collisionMargin);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setMargin: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::setLocalScaling(const btVector3 &scaling)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:98
 */
static int btBoxShape_setLocalScaling(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *scaling = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    self->setLocalScaling(*scaling);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setLocalScaling: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setLocalScaling: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::getAabb(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:110
 */
static int btBoxShape_getAabb(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btTransform *t = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *aabbMin = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *aabbMax = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    self->getAabb(*t, *aabbMin, *aabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAabb: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAabb: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::calculateLocalInertia(btScalar mass, btVector3 &inertia) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:114
 */
static int btBoxShape_calculateLocalInertia(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btScalar mass = dub::checknumber(L, 2);
    btVector3 *inertia = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    self->calculateLocalInertia(mass, *inertia);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "calculateLocalInertia: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "calculateLocalInertia: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::getPlane(btVector3 &planeNormal, btVector3 &planeSupport, int i) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:116
 */
static int btBoxShape_getPlane(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *planeNormal = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    btVector3 *planeSupport = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    int i = dub::checkint(L, 4);
    self->getPlane(*planeNormal, *planeSupport, i);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getPlane: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getPlane: Unknown exception");
  }
  return dub::error(L);
}

/** virtual int btBoxShape::getNumPlanes() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:126
 */
static int btBoxShape_getNumPlanes(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getNumPlanes());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumPlanes: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumPlanes: Unknown exception");
  }
  return dub::error(L);
}

/** virtual int btBoxShape::getNumVertices() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:131
 */
static int btBoxShape_getNumVertices(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getNumVertices());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumVertices: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumVertices: Unknown exception");
  }
  return dub::error(L);
}

/** virtual int btBoxShape::getNumEdges() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:136
 */
static int btBoxShape_getNumEdges(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getNumEdges());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumEdges: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumEdges: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::getVertex(int i, btVector3 &vtx) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:142
 */
static int btBoxShape_getVertex(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    int i = dub::checkint(L, 2);
    btVector3 *vtx = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    self->getVertex(i, *vtx);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getVertex: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getVertex: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::getPlaneEquation(btVector4 &plane, int i) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:153
 */
static int btBoxShape_getPlaneEquation(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector4 *plane = *((btVector4 **)dub::checksdata(L, 2, "bt.Vector4"));
    int i = dub::checkint(L, 3);
    self->getPlaneEquation(*plane, i);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getPlaneEquation: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getPlaneEquation: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::getEdge(int i, btVector3 &pa, btVector3 &pb) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:183
 */
static int btBoxShape_getEdge(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    int i = dub::checkint(L, 2);
    btVector3 *pa = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *pb = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    self->getEdge(i, *pa, *pb);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getEdge: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getEdge: Unknown exception");
  }
  return dub::error(L);
}

/** virtual bool btBoxShape::isInside(const btVector3 &pt, btScalar tolerance) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:254
 */
static int btBoxShape_isInside(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *pt = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    btScalar tolerance = dub::checknumber(L, 3);
    lua_pushboolean(L, self->isInside(*pt, tolerance));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isInside: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isInside: Unknown exception");
  }
  return dub::error(L);
}

/** virtual const char* btBoxShape::getName() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:272
 */
static int btBoxShape_getName(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushstring(L, self->getName());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getName: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getName: Unknown exception");
  }
  return dub::error(L);
}

/** virtual int btBoxShape::getNumPreferredPenetrationDirections() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:277
 */
static int btBoxShape_getNumPreferredPenetrationDirections(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getNumPreferredPenetrationDirections());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumPreferredPenetrationDirections: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumPreferredPenetrationDirections: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btBoxShape::getPreferredPenetrationDirection(int index, btVector3 &penetrationVector) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btBoxShape.h:282
 */
static int btBoxShape_getPreferredPenetrationDirection(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    int index = dub::checkint(L, 2);
    btVector3 *penetrationVector = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    self->getPreferredPenetrationDirection(index, *penetrationVector);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getPreferredPenetrationDirection: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getPreferredPenetrationDirection: Unknown exception");
  }
  return dub::error(L);
}

/** virtual bool btPolyhedralConvexShape::initializePolyhedralFeatures(int shiftVerticesByMargin=0)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:44
 */
static int btBoxShape_initializePolyhedralFeatures(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int shiftVerticesByMargin = dub::checkint(L, 2);
      lua_pushboolean(L, self->initializePolyhedralFeatures(shiftVerticesByMargin));
      return 1;
    } else {
      lua_pushboolean(L, self->initializePolyhedralFeatures());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "initializePolyhedralFeatures: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "initializePolyhedralFeatures: Unknown exception");
  }
  return dub::error(L);
}

/** const btConvexPolyhedron* btPolyhedralConvexShape::getConvexPolyhedron() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:46
 */
static int btBoxShape_getConvexPolyhedron(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    const btConvexPolyhedron *retval__ = self->getConvexPolyhedron();
    if (!retval__) return 0;
    dub::pushudata(L, const_cast<btConvexPolyhedron*>(retval__), "ConvexPolyhedron", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getConvexPolyhedron: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getConvexPolyhedron: Unknown exception");
  }
  return dub::error(L);
}

/** const btVector3& btConvexInternalShape::getImplicitShapeDimensions() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:56
 */
static int btBoxShape_getImplicitShapeDimensions(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    dub::pushudata(L, const_cast<btVector3*>(&self->getImplicitShapeDimensions()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getImplicitShapeDimensions: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getImplicitShapeDimensions: Unknown exception");
  }
  return dub::error(L);
}

/** void btConvexInternalShape::setImplicitShapeDimensions(const btVector3 &dimensions)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:65
 */
static int btBoxShape_setImplicitShapeDimensions(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *dimensions = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    self->setImplicitShapeDimensions(*dimensions);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setImplicitShapeDimensions: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setImplicitShapeDimensions: Unknown exception");
  }
  return dub::error(L);
}

/** void btConvexInternalShape::setSafeMargin(btScalar minDimension, btScalar defaultMarginMultiplier=0.1f)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:70
 */
static int btBoxShape_setSafeMargin(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      int type__ = lua_type(L, 2);
      if (type__ == LUA_TNUMBER) {
        btScalar minDimension = dub::checknumber(L, 2);
        btScalar defaultMarginMultiplier = dub::checknumber(L, 3);
        self->setSafeMargin(minDimension, defaultMarginMultiplier);
        return 0;
      } else {
        btVector3 *halfExtents = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
        btScalar defaultMarginMultiplier = dub::checknumber(L, 3);
        self->setSafeMargin(*halfExtents, defaultMarginMultiplier);
        return 0;
      }
    } else {
      int type__ = lua_type(L, 2);
      if (type__ == LUA_TNUMBER) {
        btScalar minDimension = dub::checknumber(L, 2);
        self->setSafeMargin(minDimension);
        return 0;
      } else {
        btVector3 *halfExtents = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
        self->setSafeMargin(*halfExtents);
        return 0;
      }
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "setSafeMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setSafeMargin: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btConvexInternalShape::getAabbSlow(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:95
 */
static int btBoxShape_getAabbSlow(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btTransform *t = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *aabbMin = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *aabbMax = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    self->getAabbSlow(*t, *aabbMin, *aabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAabbSlow: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAabbSlow: Unknown exception");
  }
  return dub::error(L);
}

/** virtual const btVector3& btConvexInternalShape::getLocalScaling() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:99
 */
static int btBoxShape_getLocalScaling(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    dub::pushudata(L, const_cast<btVector3*>(&self->getLocalScaling()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getLocalScaling: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getLocalScaling: Unknown exception");
  }
  return dub::error(L);
}

/** const btVector3& btConvexInternalShape::getLocalScalingNV() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:104
 */
static int btBoxShape_getLocalScalingNV(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    dub::pushudata(L, const_cast<btVector3*>(&self->getLocalScalingNV()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getLocalScalingNV: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getLocalScalingNV: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btScalar btConvexInternalShape::getMargin() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:113
 */
static int btBoxShape_getMargin(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getMargin());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getMargin: Unknown exception");
  }
  return dub::error(L);
}

/** btScalar btConvexInternalShape::getMarginNV() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:118
 */
static int btBoxShape_getMarginNV(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getMarginNV());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getMarginNV: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getMarginNV: Unknown exception");
  }
  return dub::error(L);
}

/** int btConvexInternalShape::calculateSerializeBufferSize() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:135
 */
static int btBoxShape_calculateSerializeBufferSize(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->calculateSerializeBufferSize());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "calculateSerializeBufferSize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "calculateSerializeBufferSize: Unknown exception");
  }
  return dub::error(L);
}

/** const char * btConvexInternalShape::serialize(void *dataBuffer, btSerializer *serializer) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:138
 */
static int btBoxShape_serialize(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    void *dataBuffer = *((void **)dub::checksdata(L, 2, "void"));
    btSerializer *serializer = *((btSerializer **)dub::checksdata(L, 3, "Serializer"));
    lua_pushstring(L, self->serialize(dataBuffer, serializer));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "serialize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "serialize: Unknown exception");
  }
  return dub::error(L);
}

/** btVector3 btConvexShape::localGetSupportVertexWithoutMarginNonVirtual(const btVector3 &vec) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:50
 */
static int btBoxShape_localGetSupportVertexWithoutMarginNonVirtual(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *vec = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    dub::pushudata(L, new btVector3(self->localGetSupportVertexWithoutMarginNonVirtual(*vec)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localGetSupportVertexWithoutMarginNonVirtual: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localGetSupportVertexWithoutMarginNonVirtual: Unknown exception");
  }
  return dub::error(L);
}

/** btVector3 btConvexShape::localGetSupportVertexNonVirtual(const btVector3 &vec) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:51
 */
static int btBoxShape_localGetSupportVertexNonVirtual(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *vec = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    dub::pushudata(L, new btVector3(self->localGetSupportVertexNonVirtual(*vec)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localGetSupportVertexNonVirtual: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localGetSupportVertexNonVirtual: Unknown exception");
  }
  return dub::error(L);
}

/** btScalar btConvexShape::getMarginNonVirtual() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:52
 */
static int btBoxShape_getMarginNonVirtual(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getMarginNonVirtual());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getMarginNonVirtual: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getMarginNonVirtual: Unknown exception");
  }
  return dub::error(L);
}

/** void btConvexShape::getAabbNonVirtual(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:53
 */
static int btBoxShape_getAabbNonVirtual(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btTransform *t = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *aabbMin = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *aabbMax = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    self->getAabbNonVirtual(*t, *aabbMin, *aabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAabbNonVirtual: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAabbNonVirtual: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btConvexShape::project(const btTransform &trans, const btVector3 &dir, btScalar &min, btScalar &max) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:55
 */
static int btBoxShape_project(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btTransform *trans = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *dir = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btScalar min = dub::checknumber(L, 4);
    btScalar max = dub::checknumber(L, 5);
    self->project(*trans, *dir, min, max);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "project: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "project: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btCollisionShape::getBoundingSphere(btVector3 &center, btScalar &radius) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:48
 */
static int btBoxShape_getBoundingSphere(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btVector3 *center = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    btScalar radius = dub::checknumber(L, 3);
    self->getBoundingSphere(*center, radius);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getBoundingSphere: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getBoundingSphere: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btScalar btCollisionShape::getAngularMotionDisc() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:51
 */
static int btBoxShape_getAngularMotionDisc(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getAngularMotionDisc());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAngularMotionDisc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAngularMotionDisc: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btScalar btCollisionShape::getContactBreakingThreshold(btScalar defaultContactThresholdFactor) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:53
 */
static int btBoxShape_getContactBreakingThreshold(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btScalar defaultContactThresholdFactor = dub::checknumber(L, 2);
    lua_pushnumber(L, self->getContactBreakingThreshold(defaultContactThresholdFactor));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getContactBreakingThreshold: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getContactBreakingThreshold: Unknown exception");
  }
  return dub::error(L);
}

/** void btCollisionShape::calculateTemporalAabb(const btTransform &curTrans, const btVector3 &linvel, const btVector3 &angvel, btScalar timeStep, btVector3 &temporalAabbMin, btVector3 &temporalAabbMax) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:58
 */
static int btBoxShape_calculateTemporalAabb(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btTransform *curTrans = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *linvel = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *angvel = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    btScalar timeStep = dub::checknumber(L, 5);
    btVector3 *temporalAabbMin = *((btVector3 **)dub::checksdata(L, 6, "bt.Vector3"));
    btVector3 *temporalAabbMax = *((btVector3 **)dub::checksdata(L, 7, "bt.Vector3"));
    self->calculateTemporalAabb(*curTrans, *linvel, *angvel, timeStep, *temporalAabbMin, *temporalAabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "calculateTemporalAabb: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "calculateTemporalAabb: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isPolyhedral() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:62
 */
static int btBoxShape_isPolyhedral(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushboolean(L, self->isPolyhedral());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isPolyhedral: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isPolyhedral: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isConvex2d() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:67
 */
static int btBoxShape_isConvex2d(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushboolean(L, self->isConvex2d());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isConvex2d: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isConvex2d: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isConvex() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:72
 */
static int btBoxShape_isConvex(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushboolean(L, self->isConvex());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isConvex: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isConvex: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isNonMoving() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:76
 */
static int btBoxShape_isNonMoving(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushboolean(L, self->isNonMoving());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isNonMoving: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isNonMoving: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isConcave() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:80
 */
static int btBoxShape_isConcave(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushboolean(L, self->isConcave());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isConcave: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isConcave: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isCompound() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:84
 */
static int btBoxShape_isCompound(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushboolean(L, self->isCompound());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isCompound: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isCompound: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isSoftBody() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:89
 */
static int btBoxShape_isSoftBody(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushboolean(L, self->isSoftBody());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isSoftBody: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isSoftBody: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isInfinite() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:95
 */
static int btBoxShape_isInfinite(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushboolean(L, self->isInfinite());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isInfinite: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isInfinite: Unknown exception");
  }
  return dub::error(L);
}

/** int btCollisionShape::getShapeType() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:111
 */
static int btBoxShape_getShapeType(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    lua_pushnumber(L, self->getShapeType());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getShapeType: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getShapeType: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btVector3 btCollisionShape::getAnisotropicRollingFrictionDirection() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:115
 */
static int btBoxShape_getAnisotropicRollingFrictionDirection(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    dub::pushudata(L, new btVector3(self->getAnisotropicRollingFrictionDirection()), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAnisotropicRollingFrictionDirection: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAnisotropicRollingFrictionDirection: Unknown exception");
  }
  return dub::error(L);
}

/** void btCollisionShape::setUserPointer(void *userPtr)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:124
 */
static int btBoxShape_setUserPointer(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    void *userPtr = *((void **)dub::checksdata(L, 2, "void"));
    self->setUserPointer(userPtr);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setUserPointer: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setUserPointer: Unknown exception");
  }
  return dub::error(L);
}

/** void* btCollisionShape::getUserPointer() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:129
 */
static int btBoxShape_getUserPointer(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    self->getUserPointer();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getUserPointer: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getUserPointer: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btCollisionShape::serializeSingleShape(btSerializer *serializer) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:139
 */
static int btBoxShape_serializeSingleShape(lua_State *L) {
  try {
    btBoxShape *self = *((btBoxShape **)dub::checksdata(L, 1, "bt.BoxShape"));
    btSerializer *serializer = *((btSerializer **)dub::checksdata(L, 2, "Serializer"));
    self->serializeSingleShape(serializer);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "serializeSingleShape: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "serializeSingleShape: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int btBoxShape___tostring(lua_State *L) {
  btBoxShape *self = *((btBoxShape **)dub::checksdata_n(L, 1, "bt.BoxShape"));
  lua_pushfstring(L, "bt.BoxShape: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg btBoxShape_member_methods[] = {
  { "__gc"         , btBoxShape__btBoxShape },
  { "_cast_"       , btBoxShape__cast_    },
  { "getHalfExtentsWithMargin", btBoxShape_getHalfExtentsWithMargin },
  { "getHalfExtentsWithoutMargin", btBoxShape_getHalfExtentsWithoutMargin },
  { "localGetSupportingVertex", btBoxShape_localGetSupportingVertex },
  { "localGetSupportingVertexWithoutMargin", btBoxShape_localGetSupportingVertexWithoutMargin },
  { "batchedUnitVectorGetSupportingVertexWithoutMargin", btBoxShape_batchedUnitVectorGetSupportingVertexWithoutMargin },
  { "new"          , btBoxShape_btBoxShape },
  { "setMargin"    , btBoxShape_setMargin },
  { "setLocalScaling", btBoxShape_setLocalScaling },
  { "getAabb"      , btBoxShape_getAabb   },
  { "calculateLocalInertia", btBoxShape_calculateLocalInertia },
  { "getPlane"     , btBoxShape_getPlane  },
  { "getNumPlanes" , btBoxShape_getNumPlanes },
  { "getNumVertices", btBoxShape_getNumVertices },
  { "getNumEdges"  , btBoxShape_getNumEdges },
  { "getVertex"    , btBoxShape_getVertex },
  { "getPlaneEquation", btBoxShape_getPlaneEquation },
  { "getEdge"      , btBoxShape_getEdge   },
  { "isInside"     , btBoxShape_isInside  },
  { "getName"      , btBoxShape_getName   },
  { "getNumPreferredPenetrationDirections", btBoxShape_getNumPreferredPenetrationDirections },
  { "getPreferredPenetrationDirection", btBoxShape_getPreferredPenetrationDirection },
  { "initializePolyhedralFeatures", btBoxShape_initializePolyhedralFeatures },
  { "getConvexPolyhedron", btBoxShape_getConvexPolyhedron },
  { "getImplicitShapeDimensions", btBoxShape_getImplicitShapeDimensions },
  { "setImplicitShapeDimensions", btBoxShape_setImplicitShapeDimensions },
  { "setSafeMargin", btBoxShape_setSafeMargin },
  { "getAabbSlow"  , btBoxShape_getAabbSlow },
  { "getLocalScaling", btBoxShape_getLocalScaling },
  { "getLocalScalingNV", btBoxShape_getLocalScalingNV },
  { "getMargin"    , btBoxShape_getMargin },
  { "getMarginNV"  , btBoxShape_getMarginNV },
  { "calculateSerializeBufferSize", btBoxShape_calculateSerializeBufferSize },
  { "serialize"    , btBoxShape_serialize },
  { "localGetSupportVertexWithoutMarginNonVirtual", btBoxShape_localGetSupportVertexWithoutMarginNonVirtual },
  { "localGetSupportVertexNonVirtual", btBoxShape_localGetSupportVertexNonVirtual },
  { "getMarginNonVirtual", btBoxShape_getMarginNonVirtual },
  { "getAabbNonVirtual", btBoxShape_getAabbNonVirtual },
  { "project"      , btBoxShape_project   },
  { "getBoundingSphere", btBoxShape_getBoundingSphere },
  { "getAngularMotionDisc", btBoxShape_getAngularMotionDisc },
  { "getContactBreakingThreshold", btBoxShape_getContactBreakingThreshold },
  { "calculateTemporalAabb", btBoxShape_calculateTemporalAabb },
  { "isPolyhedral" , btBoxShape_isPolyhedral },
  { "isConvex2d"   , btBoxShape_isConvex2d },
  { "isConvex"     , btBoxShape_isConvex  },
  { "isNonMoving"  , btBoxShape_isNonMoving },
  { "isConcave"    , btBoxShape_isConcave },
  { "isCompound"   , btBoxShape_isCompound },
  { "isSoftBody"   , btBoxShape_isSoftBody },
  { "isInfinite"   , btBoxShape_isInfinite },
  { "getShapeType" , btBoxShape_getShapeType },
  { "getAnisotropicRollingFrictionDirection", btBoxShape_getAnisotropicRollingFrictionDirection },
  { "setUserPointer", btBoxShape_setUserPointer },
  { "getUserPointer", btBoxShape_getUserPointer },
  { "serializeSingleShape", btBoxShape_serializeSingleShape },
  { "__tostring"   , btBoxShape___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_bt_BoxShape(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "bt.BoxShape");
  // <mt>

  // register member methods
  dub::fregister(L, btBoxShape_member_methods);
  // setup meta-table
  dub::setup(L, "bt.BoxShape");
  // <mt>
  return 1;
}
