/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class btPolyhedralConvexShape
 *
 * This file has been generated by dub 2.2.1.
 */
#include "dub/dub.h"
#include "BulletCollision/CollisionShapes/btPolyhedralConvexShape.h"


/** Cast (class_name)
 * 
 */
static int btPolyhedralConvexShape__cast_(lua_State *L) {

  btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata_n(L, 1, "bt.PolyhedralConvexShape"));
  const char *key = luaL_checkstring(L, 2);
  void **retval__ = (void**)lua_newuserdata(L, sizeof(void*));
  int key_h = dub::hash(key, 3);
  switch(key_h) {
    case 0: {
      if (DUB_ASSERT_KEY(key, "bt.ConvexInternalShape")) break;
      *retval__ = static_cast<btConvexInternalShape *>(self);
      return 1;
    }
    case 1: {
      if (DUB_ASSERT_KEY(key, "bt.ConvexShape")) break;
      *retval__ = static_cast<btConvexShape *>(self);
      return 1;
    }
    case 2: {
      if (DUB_ASSERT_KEY(key, "bt.CollisionShape")) break;
      *retval__ = static_cast<btCollisionShape *>(self);
      return 1;
    }
  }
  return 0;
}

/** virtual btPolyhedralConvexShape::~btPolyhedralConvexShape()
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:40
 */
static int btPolyhedralConvexShape__btPolyhedralConvexShape(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "bt.PolyhedralConvexShape"));
    if (userdata->gc) {
      btPolyhedralConvexShape *self = (btPolyhedralConvexShape *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** virtual bool btPolyhedralConvexShape::initializePolyhedralFeatures(int shiftVerticesByMargin=0)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:44
 */
static int btPolyhedralConvexShape_initializePolyhedralFeatures(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    int top__ = lua_gettop(L);
    if (top__ >= 2) {
      int shiftVerticesByMargin = dub::checkint(L, 2);
      lua_pushboolean(L, self->initializePolyhedralFeatures(shiftVerticesByMargin));
      return 1;
    } else {
      lua_pushboolean(L, self->initializePolyhedralFeatures());
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "initializePolyhedralFeatures: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "initializePolyhedralFeatures: Unknown exception");
  }
  return dub::error(L);
}

/** const btConvexPolyhedron* btPolyhedralConvexShape::getConvexPolyhedron() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:46
 */
static int btPolyhedralConvexShape_getConvexPolyhedron(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    const btConvexPolyhedron *retval__ = self->getConvexPolyhedron();
    if (!retval__) return 0;
    dub::pushudata(L, const_cast<btConvexPolyhedron*>(retval__), "ConvexPolyhedron", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getConvexPolyhedron: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getConvexPolyhedron: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btVector3 btPolyhedralConvexShape::localGetSupportingVertexWithoutMargin(const btVector3 &vec) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:53
 */
static int btPolyhedralConvexShape_localGetSupportingVertexWithoutMargin(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *vec = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    dub::pushudata(L, new btVector3(self->localGetSupportingVertexWithoutMargin(*vec)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localGetSupportingVertexWithoutMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localGetSupportingVertexWithoutMargin: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btPolyhedralConvexShape::batchedUnitVectorGetSupportingVertexWithoutMargin(const btVector3 *vectors, btVector3 *supportVerticesOut, int numVectors) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:54
 */
static int btPolyhedralConvexShape_batchedUnitVectorGetSupportingVertexWithoutMargin(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *vectors = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    btVector3 *supportVerticesOut = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    int numVectors = dub::checkint(L, 4);
    self->batchedUnitVectorGetSupportingVertexWithoutMargin(vectors, supportVerticesOut, numVectors);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "batchedUnitVectorGetSupportingVertexWithoutMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "batchedUnitVectorGetSupportingVertexWithoutMargin: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btPolyhedralConvexShape::calculateLocalInertia(btScalar mass, btVector3 &inertia) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:56
 */
static int btPolyhedralConvexShape_calculateLocalInertia(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btScalar mass = dub::checknumber(L, 2);
    btVector3 *inertia = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    self->calculateLocalInertia(mass, *inertia);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "calculateLocalInertia: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "calculateLocalInertia: Unknown exception");
  }
  return dub::error(L);
}

/** virtual int btPolyhedralConvexShape::getNumVertices() const =0
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:59
 */
static int btPolyhedralConvexShape_getNumVertices(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getNumVertices());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumVertices: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumVertices: Unknown exception");
  }
  return dub::error(L);
}

/** virtual int btPolyhedralConvexShape::getNumEdges() const =0
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:60
 */
static int btPolyhedralConvexShape_getNumEdges(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getNumEdges());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumEdges: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumEdges: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btPolyhedralConvexShape::getEdge(int i, btVector3 &pa, btVector3 &pb) const =0
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:61
 */
static int btPolyhedralConvexShape_getEdge(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    int i = dub::checkint(L, 2);
    btVector3 *pa = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *pb = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    self->getEdge(i, *pa, *pb);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getEdge: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getEdge: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btPolyhedralConvexShape::getVertex(int i, btVector3 &vtx) const =0
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:62
 */
static int btPolyhedralConvexShape_getVertex(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    int i = dub::checkint(L, 2);
    btVector3 *vtx = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    self->getVertex(i, *vtx);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getVertex: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getVertex: Unknown exception");
  }
  return dub::error(L);
}

/** virtual int btPolyhedralConvexShape::getNumPlanes() const =0
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:63
 */
static int btPolyhedralConvexShape_getNumPlanes(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getNumPlanes());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumPlanes: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumPlanes: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btPolyhedralConvexShape::getPlane(btVector3 &planeNormal, btVector3 &planeSupport, int i) const =0
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:64
 */
static int btPolyhedralConvexShape_getPlane(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *planeNormal = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    btVector3 *planeSupport = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    int i = dub::checkint(L, 4);
    self->getPlane(*planeNormal, *planeSupport, i);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getPlane: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getPlane: Unknown exception");
  }
  return dub::error(L);
}

/** virtual bool btPolyhedralConvexShape::isInside(const btVector3 &pt, btScalar tolerance) const =0
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h:67
 */
static int btPolyhedralConvexShape_isInside(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *pt = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    btScalar tolerance = dub::checknumber(L, 3);
    lua_pushboolean(L, self->isInside(*pt, tolerance));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isInside: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isInside: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btVector3 btConvexInternalShape::localGetSupportingVertex(const btVector3 &vec) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:54
 */
static int btPolyhedralConvexShape_localGetSupportingVertex(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *vec = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    dub::pushudata(L, new btVector3(self->localGetSupportingVertex(*vec)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localGetSupportingVertex: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localGetSupportingVertex: Unknown exception");
  }
  return dub::error(L);
}

/** const btVector3& btConvexInternalShape::getImplicitShapeDimensions() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:56
 */
static int btPolyhedralConvexShape_getImplicitShapeDimensions(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    dub::pushudata(L, const_cast<btVector3*>(&self->getImplicitShapeDimensions()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getImplicitShapeDimensions: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getImplicitShapeDimensions: Unknown exception");
  }
  return dub::error(L);
}

/** void btConvexInternalShape::setImplicitShapeDimensions(const btVector3 &dimensions)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:65
 */
static int btPolyhedralConvexShape_setImplicitShapeDimensions(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *dimensions = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    self->setImplicitShapeDimensions(*dimensions);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setImplicitShapeDimensions: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setImplicitShapeDimensions: Unknown exception");
  }
  return dub::error(L);
}

/** void btConvexInternalShape::setSafeMargin(btScalar minDimension, btScalar defaultMarginMultiplier=0.1f)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:70
 */
static int btPolyhedralConvexShape_setSafeMargin(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    int top__ = lua_gettop(L);
    if (top__ >= 3) {
      int type__ = lua_type(L, 2);
      if (type__ == LUA_TNUMBER) {
        btScalar minDimension = dub::checknumber(L, 2);
        btScalar defaultMarginMultiplier = dub::checknumber(L, 3);
        self->setSafeMargin(minDimension, defaultMarginMultiplier);
        return 0;
      } else {
        btVector3 *halfExtents = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
        btScalar defaultMarginMultiplier = dub::checknumber(L, 3);
        self->setSafeMargin(*halfExtents, defaultMarginMultiplier);
        return 0;
      }
    } else {
      int type__ = lua_type(L, 2);
      if (type__ == LUA_TNUMBER) {
        btScalar minDimension = dub::checknumber(L, 2);
        self->setSafeMargin(minDimension);
        return 0;
      } else {
        btVector3 *halfExtents = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
        self->setSafeMargin(*halfExtents);
        return 0;
      }
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "setSafeMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setSafeMargin: Unknown exception");
  }
  return dub::error(L);
}

/** void btConvexInternalShape::getAabb(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:88
 */
static int btPolyhedralConvexShape_getAabb(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btTransform *t = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *aabbMin = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *aabbMax = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    self->getAabb(*t, *aabbMin, *aabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAabb: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAabb: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btConvexInternalShape::getAabbSlow(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:95
 */
static int btPolyhedralConvexShape_getAabbSlow(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btTransform *t = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *aabbMin = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *aabbMax = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    self->getAabbSlow(*t, *aabbMin, *aabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAabbSlow: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAabbSlow: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btConvexInternalShape::setLocalScaling(const btVector3 &scaling)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:98
 */
static int btPolyhedralConvexShape_setLocalScaling(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *scaling = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    self->setLocalScaling(*scaling);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setLocalScaling: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setLocalScaling: Unknown exception");
  }
  return dub::error(L);
}

/** virtual const btVector3& btConvexInternalShape::getLocalScaling() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:99
 */
static int btPolyhedralConvexShape_getLocalScaling(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    dub::pushudata(L, const_cast<btVector3*>(&self->getLocalScaling()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getLocalScaling: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getLocalScaling: Unknown exception");
  }
  return dub::error(L);
}

/** const btVector3& btConvexInternalShape::getLocalScalingNV() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:104
 */
static int btPolyhedralConvexShape_getLocalScalingNV(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    dub::pushudata(L, const_cast<btVector3*>(&self->getLocalScalingNV()), "bt.Vector3", false);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getLocalScalingNV: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getLocalScalingNV: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btConvexInternalShape::setMargin(btScalar margin)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:109
 */
static int btPolyhedralConvexShape_setMargin(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btScalar margin = dub::checknumber(L, 2);
    self->setMargin(margin);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setMargin: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btScalar btConvexInternalShape::getMargin() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:113
 */
static int btPolyhedralConvexShape_getMargin(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getMargin());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getMargin: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getMargin: Unknown exception");
  }
  return dub::error(L);
}

/** btScalar btConvexInternalShape::getMarginNV() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:118
 */
static int btPolyhedralConvexShape_getMarginNV(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getMarginNV());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getMarginNV: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getMarginNV: Unknown exception");
  }
  return dub::error(L);
}

/** virtual int btConvexInternalShape::getNumPreferredPenetrationDirections() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:123
 */
static int btPolyhedralConvexShape_getNumPreferredPenetrationDirections(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getNumPreferredPenetrationDirections());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getNumPreferredPenetrationDirections: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getNumPreferredPenetrationDirections: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btConvexInternalShape::getPreferredPenetrationDirection(int index, btVector3 &penetrationVector) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:128
 */
static int btPolyhedralConvexShape_getPreferredPenetrationDirection(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    int index = dub::checkint(L, 2);
    btVector3 *penetrationVector = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    self->getPreferredPenetrationDirection(index, *penetrationVector);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getPreferredPenetrationDirection: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getPreferredPenetrationDirection: Unknown exception");
  }
  return dub::error(L);
}

/** int btConvexInternalShape::calculateSerializeBufferSize() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:135
 */
static int btPolyhedralConvexShape_calculateSerializeBufferSize(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->calculateSerializeBufferSize());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "calculateSerializeBufferSize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "calculateSerializeBufferSize: Unknown exception");
  }
  return dub::error(L);
}

/** const char * btConvexInternalShape::serialize(void *dataBuffer, btSerializer *serializer) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexInternalShape.h:138
 */
static int btPolyhedralConvexShape_serialize(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    void *dataBuffer = *((void **)dub::checksdata(L, 2, "void"));
    btSerializer *serializer = *((btSerializer **)dub::checksdata(L, 3, "Serializer"));
    lua_pushstring(L, self->serialize(dataBuffer, serializer));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "serialize: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "serialize: Unknown exception");
  }
  return dub::error(L);
}

/** btVector3 btConvexShape::localGetSupportVertexWithoutMarginNonVirtual(const btVector3 &vec) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:50
 */
static int btPolyhedralConvexShape_localGetSupportVertexWithoutMarginNonVirtual(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *vec = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    dub::pushudata(L, new btVector3(self->localGetSupportVertexWithoutMarginNonVirtual(*vec)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localGetSupportVertexWithoutMarginNonVirtual: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localGetSupportVertexWithoutMarginNonVirtual: Unknown exception");
  }
  return dub::error(L);
}

/** btVector3 btConvexShape::localGetSupportVertexNonVirtual(const btVector3 &vec) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:51
 */
static int btPolyhedralConvexShape_localGetSupportVertexNonVirtual(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *vec = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    dub::pushudata(L, new btVector3(self->localGetSupportVertexNonVirtual(*vec)), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "localGetSupportVertexNonVirtual: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "localGetSupportVertexNonVirtual: Unknown exception");
  }
  return dub::error(L);
}

/** btScalar btConvexShape::getMarginNonVirtual() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:52
 */
static int btPolyhedralConvexShape_getMarginNonVirtual(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getMarginNonVirtual());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getMarginNonVirtual: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getMarginNonVirtual: Unknown exception");
  }
  return dub::error(L);
}

/** void btConvexShape::getAabbNonVirtual(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:53
 */
static int btPolyhedralConvexShape_getAabbNonVirtual(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btTransform *t = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *aabbMin = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *aabbMax = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    self->getAabbNonVirtual(*t, *aabbMin, *aabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAabbNonVirtual: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAabbNonVirtual: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btConvexShape::project(const btTransform &trans, const btVector3 &dir, btScalar &min, btScalar &max) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btConvexShape.h:55
 */
static int btPolyhedralConvexShape_project(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btTransform *trans = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *dir = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btScalar min = dub::checknumber(L, 4);
    btScalar max = dub::checknumber(L, 5);
    self->project(*trans, *dir, min, max);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "project: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "project: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btCollisionShape::getBoundingSphere(btVector3 &center, btScalar &radius) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:48
 */
static int btPolyhedralConvexShape_getBoundingSphere(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btVector3 *center = *((btVector3 **)dub::checksdata(L, 2, "bt.Vector3"));
    btScalar radius = dub::checknumber(L, 3);
    self->getBoundingSphere(*center, radius);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getBoundingSphere: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getBoundingSphere: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btScalar btCollisionShape::getAngularMotionDisc() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:51
 */
static int btPolyhedralConvexShape_getAngularMotionDisc(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getAngularMotionDisc());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAngularMotionDisc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAngularMotionDisc: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btScalar btCollisionShape::getContactBreakingThreshold(btScalar defaultContactThresholdFactor) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:53
 */
static int btPolyhedralConvexShape_getContactBreakingThreshold(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btScalar defaultContactThresholdFactor = dub::checknumber(L, 2);
    lua_pushnumber(L, self->getContactBreakingThreshold(defaultContactThresholdFactor));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getContactBreakingThreshold: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getContactBreakingThreshold: Unknown exception");
  }
  return dub::error(L);
}

/** void btCollisionShape::calculateTemporalAabb(const btTransform &curTrans, const btVector3 &linvel, const btVector3 &angvel, btScalar timeStep, btVector3 &temporalAabbMin, btVector3 &temporalAabbMax) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:58
 */
static int btPolyhedralConvexShape_calculateTemporalAabb(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btTransform *curTrans = *((btTransform **)dub::checksdata(L, 2, "bt.Transform"));
    btVector3 *linvel = *((btVector3 **)dub::checksdata(L, 3, "bt.Vector3"));
    btVector3 *angvel = *((btVector3 **)dub::checksdata(L, 4, "bt.Vector3"));
    btScalar timeStep = dub::checknumber(L, 5);
    btVector3 *temporalAabbMin = *((btVector3 **)dub::checksdata(L, 6, "bt.Vector3"));
    btVector3 *temporalAabbMax = *((btVector3 **)dub::checksdata(L, 7, "bt.Vector3"));
    self->calculateTemporalAabb(*curTrans, *linvel, *angvel, timeStep, *temporalAabbMin, *temporalAabbMax);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "calculateTemporalAabb: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "calculateTemporalAabb: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isPolyhedral() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:62
 */
static int btPolyhedralConvexShape_isPolyhedral(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushboolean(L, self->isPolyhedral());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isPolyhedral: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isPolyhedral: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isConvex2d() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:67
 */
static int btPolyhedralConvexShape_isConvex2d(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushboolean(L, self->isConvex2d());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isConvex2d: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isConvex2d: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isConvex() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:72
 */
static int btPolyhedralConvexShape_isConvex(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushboolean(L, self->isConvex());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isConvex: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isConvex: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isNonMoving() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:76
 */
static int btPolyhedralConvexShape_isNonMoving(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushboolean(L, self->isNonMoving());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isNonMoving: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isNonMoving: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isConcave() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:80
 */
static int btPolyhedralConvexShape_isConcave(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushboolean(L, self->isConcave());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isConcave: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isConcave: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isCompound() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:84
 */
static int btPolyhedralConvexShape_isCompound(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushboolean(L, self->isCompound());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isCompound: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isCompound: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isSoftBody() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:89
 */
static int btPolyhedralConvexShape_isSoftBody(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushboolean(L, self->isSoftBody());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isSoftBody: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isSoftBody: Unknown exception");
  }
  return dub::error(L);
}

/** bool btCollisionShape::isInfinite() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:95
 */
static int btPolyhedralConvexShape_isInfinite(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushboolean(L, self->isInfinite());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "isInfinite: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "isInfinite: Unknown exception");
  }
  return dub::error(L);
}

/** virtual const char* btCollisionShape::getName() const =0
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:107
 */
static int btPolyhedralConvexShape_getName(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushstring(L, self->getName());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getName: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getName: Unknown exception");
  }
  return dub::error(L);
}

/** int btCollisionShape::getShapeType() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:111
 */
static int btPolyhedralConvexShape_getShapeType(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    lua_pushnumber(L, self->getShapeType());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getShapeType: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getShapeType: Unknown exception");
  }
  return dub::error(L);
}

/** virtual btVector3 btCollisionShape::getAnisotropicRollingFrictionDirection() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:115
 */
static int btPolyhedralConvexShape_getAnisotropicRollingFrictionDirection(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    dub::pushudata(L, new btVector3(self->getAnisotropicRollingFrictionDirection()), "bt.Vector3", true);
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getAnisotropicRollingFrictionDirection: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getAnisotropicRollingFrictionDirection: Unknown exception");
  }
  return dub::error(L);
}

/** void btCollisionShape::setUserPointer(void *userPtr)
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:124
 */
static int btPolyhedralConvexShape_setUserPointer(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    void *userPtr = *((void **)dub::checksdata(L, 2, "void"));
    self->setUserPointer(userPtr);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "setUserPointer: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "setUserPointer: Unknown exception");
  }
  return dub::error(L);
}

/** void* btCollisionShape::getUserPointer() const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:129
 */
static int btPolyhedralConvexShape_getUserPointer(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    self->getUserPointer();
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "getUserPointer: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "getUserPointer: Unknown exception");
  }
  return dub::error(L);
}

/** virtual void btCollisionShape::serializeSingleShape(btSerializer *serializer) const
 * src/vendor/bullet/src/BulletCollision/CollisionShapes/btCollisionShape.h:139
 */
static int btPolyhedralConvexShape_serializeSingleShape(lua_State *L) {
  try {
    btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata(L, 1, "bt.PolyhedralConvexShape"));
    btSerializer *serializer = *((btSerializer **)dub::checksdata(L, 2, "Serializer"));
    self->serializeSingleShape(serializer);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "serializeSingleShape: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "serializeSingleShape: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int btPolyhedralConvexShape___tostring(lua_State *L) {
  btPolyhedralConvexShape *self = *((btPolyhedralConvexShape **)dub::checksdata_n(L, 1, "bt.PolyhedralConvexShape"));
  lua_pushfstring(L, "bt.PolyhedralConvexShape: %p", self);
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg btPolyhedralConvexShape_member_methods[] = {
  { "_cast_"       , btPolyhedralConvexShape__cast_ },
  { "__gc"         , btPolyhedralConvexShape__btPolyhedralConvexShape },
  { "initializePolyhedralFeatures", btPolyhedralConvexShape_initializePolyhedralFeatures },
  { "getConvexPolyhedron", btPolyhedralConvexShape_getConvexPolyhedron },
  { "localGetSupportingVertexWithoutMargin", btPolyhedralConvexShape_localGetSupportingVertexWithoutMargin },
  { "batchedUnitVectorGetSupportingVertexWithoutMargin", btPolyhedralConvexShape_batchedUnitVectorGetSupportingVertexWithoutMargin },
  { "calculateLocalInertia", btPolyhedralConvexShape_calculateLocalInertia },
  { "getNumVertices", btPolyhedralConvexShape_getNumVertices },
  { "getNumEdges"  , btPolyhedralConvexShape_getNumEdges },
  { "getEdge"      , btPolyhedralConvexShape_getEdge },
  { "getVertex"    , btPolyhedralConvexShape_getVertex },
  { "getNumPlanes" , btPolyhedralConvexShape_getNumPlanes },
  { "getPlane"     , btPolyhedralConvexShape_getPlane },
  { "isInside"     , btPolyhedralConvexShape_isInside },
  { "localGetSupportingVertex", btPolyhedralConvexShape_localGetSupportingVertex },
  { "getImplicitShapeDimensions", btPolyhedralConvexShape_getImplicitShapeDimensions },
  { "setImplicitShapeDimensions", btPolyhedralConvexShape_setImplicitShapeDimensions },
  { "setSafeMargin", btPolyhedralConvexShape_setSafeMargin },
  { "getAabb"      , btPolyhedralConvexShape_getAabb },
  { "getAabbSlow"  , btPolyhedralConvexShape_getAabbSlow },
  { "setLocalScaling", btPolyhedralConvexShape_setLocalScaling },
  { "getLocalScaling", btPolyhedralConvexShape_getLocalScaling },
  { "getLocalScalingNV", btPolyhedralConvexShape_getLocalScalingNV },
  { "setMargin"    , btPolyhedralConvexShape_setMargin },
  { "getMargin"    , btPolyhedralConvexShape_getMargin },
  { "getMarginNV"  , btPolyhedralConvexShape_getMarginNV },
  { "getNumPreferredPenetrationDirections", btPolyhedralConvexShape_getNumPreferredPenetrationDirections },
  { "getPreferredPenetrationDirection", btPolyhedralConvexShape_getPreferredPenetrationDirection },
  { "calculateSerializeBufferSize", btPolyhedralConvexShape_calculateSerializeBufferSize },
  { "serialize"    , btPolyhedralConvexShape_serialize },
  { "localGetSupportVertexWithoutMarginNonVirtual", btPolyhedralConvexShape_localGetSupportVertexWithoutMarginNonVirtual },
  { "localGetSupportVertexNonVirtual", btPolyhedralConvexShape_localGetSupportVertexNonVirtual },
  { "getMarginNonVirtual", btPolyhedralConvexShape_getMarginNonVirtual },
  { "getAabbNonVirtual", btPolyhedralConvexShape_getAabbNonVirtual },
  { "project"      , btPolyhedralConvexShape_project },
  { "getBoundingSphere", btPolyhedralConvexShape_getBoundingSphere },
  { "getAngularMotionDisc", btPolyhedralConvexShape_getAngularMotionDisc },
  { "getContactBreakingThreshold", btPolyhedralConvexShape_getContactBreakingThreshold },
  { "calculateTemporalAabb", btPolyhedralConvexShape_calculateTemporalAabb },
  { "isPolyhedral" , btPolyhedralConvexShape_isPolyhedral },
  { "isConvex2d"   , btPolyhedralConvexShape_isConvex2d },
  { "isConvex"     , btPolyhedralConvexShape_isConvex },
  { "isNonMoving"  , btPolyhedralConvexShape_isNonMoving },
  { "isConcave"    , btPolyhedralConvexShape_isConcave },
  { "isCompound"   , btPolyhedralConvexShape_isCompound },
  { "isSoftBody"   , btPolyhedralConvexShape_isSoftBody },
  { "isInfinite"   , btPolyhedralConvexShape_isInfinite },
  { "getName"      , btPolyhedralConvexShape_getName },
  { "getShapeType" , btPolyhedralConvexShape_getShapeType },
  { "getAnisotropicRollingFrictionDirection", btPolyhedralConvexShape_getAnisotropicRollingFrictionDirection },
  { "setUserPointer", btPolyhedralConvexShape_setUserPointer },
  { "getUserPointer", btPolyhedralConvexShape_getUserPointer },
  { "serializeSingleShape", btPolyhedralConvexShape_serializeSingleShape },
  { "__tostring"   , btPolyhedralConvexShape___tostring },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_bt_PolyhedralConvexShape(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "bt.PolyhedralConvexShape");
  // <mt>

  // register member methods
  dub::fregister(L, btPolyhedralConvexShape_member_methods);
  // setup meta-table
  dub::setup(L, "bt.PolyhedralConvexShape");
  // <mt>
  return 1;
}
